# Generated by Django 4.2.7 on 2023-11-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('dni', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=25)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.role')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_recojo', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_cliente', to='administrador.user')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_repartidor', to='administrador.user')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.servicio')),
            ],
        ),
    ]
