# Generated by Django 4.2.7 on 2023-12-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_image', models.ImageField(upload_to='Ofertas/')),
                ('titulo', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
                ('articleDateTime', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(null=True, upload_to='productos/')),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('dni', models.CharField(max_length=8)),
                ('avatar', models.ImageField(default='imagenes/profile.jpg', null=True, upload_to='imagenes/')),
                ('password', models.CharField(max_length=100)),
                ('estado_repartidor', models.BooleanField(blank=True, default=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('proceso_terminado', 'Proceso Terminado'), ('en_camino', 'En camino'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('cantidad_prendas', models.IntegerField()),
                ('tipo_entrega', models.CharField(choices=[('1', 'Recojo y envio a domicilio'), ('2', 'Recojo a Domicilio')], default='1', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_cliente', to='administrador.user')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_repartidor', to='administrador.user')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.servicio')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('transaccion_id', models.CharField(max_length=255)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.pedido')),
            ],
            options={
                'db_table': 'Pagos',
            },
        ),
    ]
