# Generated by Django 4.2.7 on 2023-11-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='servicios',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
