# Generated by Django 4.2.7 on 2023-11-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='precio_unitario',
            new_name='precio',
        ),
    ]
