# Generated by Django 4.2.7 on 2023-11-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_rename_precio_unitario_pedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='imagenes/defaultAvatar.jpg', upload_to='imagenes/'),
        ),
    ]
