# Generated by Django 4.2.7 on 2023-11-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaultImg/defaultAvatar.jpg', upload_to='imagenes/'),
        ),
    ]
