# Generated by Django 4.2.7 on 2023-11-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_recojo',
            new_name='fecha_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='precio',
            new_name='precio_total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_como_repartidor', to='administrador.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='imagenes/default.jpg', upload_to='imagenes/'),
        ),
    ]
