# Generated by Django 4.2.7 on 2023-11-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_rename_fecha_recojo_pedido_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('1', 'Recojo y envio a domicilio'), ('2', 'Recojo a Domicilio')], default='recojo', max_length=10),
        ),
    ]
