# Generated by Django 4.2.7 on 2023-11-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_pedido_descripcion_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('1', 'Recojo y envio a domicilio'), ('2', 'Recojo a Domicilio')], default='1', max_length=10),
        ),
    ]
